engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCasePropertyName:
        enabled: true
        allow-underscore: true
      Controversial/CamelCaseMethodName:
        enabled: true
        allow-underscore: true
      CleanCode/StaticAccess:
        enabled: false
      Design/TooManyMethods:
        enabled: true
        maxmethods: 25
      Design/TooManyPublicMethods:
        enabled: false
        maxmethods: 25
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
ratings:
  paths:
  - "**.php"
exclude_paths:
- .git/**/*