engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCasePropertyName:
        enabled: true
        allow-underscore: on
      Controversial/CamelCaseMethodName:
        enabled: true
        allow-underscore: on
      CleanCode/StaticAccess:
        enabled: false
      Design/TooManyMethods:
        enabled: true
        maxmethods: 25
      Design/TooManyPublicMethods:
        enabled: true
        maxmethods: 25
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: []