engines:
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "controversial,design,naming,unusedcode,phpmd.xml"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
ratings:
  paths:
  - "**.php"
exclude_paths:
- .git/**/*
